### ISSUE TITLE
Error Downloading - not supported between instances

### ISSUE THREAD

**Issue by stetay2233** [TheWicklowWolf/LidaTube#14]
Running docker on Unraid

Settings connected between Lidarr instance can successfully search for matches, but get met with the below error for every match song

Error Downloading: '<' not supported between instances of 'int' and 'str'

**Comment by TheWicklowWolf** [comment]
Are you running the latest version? Not sure how you do it in Unraid but to pull the latest version `docker compose pull && docker compose up -d `
What environmental variables are you using? I'm pretty sure that was an issue with older versions and should be fixed (it was caused where environmental variables were parsed incorrectly)

**Comment by TheWicklowWolf** [comment]
I can see you're using the `latest` tag but when did you pull that image? I can't replicate this issue but I'm also not running unraid so I'm not sure if it's something specific to unraid. 
Can you either delete the image and the container and then recreate or try this:


**docker pull thewicklowwolf/lidatube:latest &&**
docker run
-d
--name='lidatube'
--net='bridge'
-e TZ="America/Chicago"
-e HOST_OS="Unraid"
-e HOST_HOSTNAME=""
-e HOST_CONTAINERNAME="lidatube"
-e 'lidarr_address'='http://:8686'
-e 'lidarr_api_key'='MyAPIKey'
-e 'thread_limit'='1'
-e 'PGID'='100'
-e 'PUID'='99'
-l net.unraid.docker.managed=dockerman
-l net.unraid.docker.webui='http://[IP]:[PORT:5000]'
-l net.unraid.docker.icon='https://user-images.githubusercontent.com/111055425/272870500-69396f7a-af18-42a9-b1ea-0585b488bdec.png'
-p '5000:5000/tcp'
-v '/mnt/user/Media/Music/':'/lidatube/downloads':'rw,shared'
-v '/etc/localtime':'/etc/localtime':'ro' 'thewicklowwolf/lidatube:latest'

**Comment by TheWicklowWolf** [comment]
also you can mount a path to the config folder, and check the settings there:

```yml
  volumes:
      - /path/to/config:/lidatube/config
 ```

**Comment by stetay2233** [comment]
> also you can mount a path to the config folder, and check the settings there:
> 
> ```yaml
>   volumes:
>       - /path/to/config:/lidatube/config
> ```

Thanks for the suggestions and support

Got this added, ran into a permission issue but got the mapping to work and the setting_config.json in there and reading correctly at startup

but still getting the same response for all downloads:

Error Downloading: '<' not supported between instances of 'int' and 'str'

there is probably something either unique to unraid or my setup here if you have not seen this before

i do have other tools leveraging yt-dlp that can successfully download, but not in the manner this tool would be helpful

**Comment by TheWicklowWolf** [comment]
I think I have a potential fix, although I'm not entirely sure if this issue is masking another underlying problem.
Try it and see how it goes.

see 907f8ceda2909c574fa433fa511310653c889ac1

**Comment by stetay2233** [comment]
> I think I have a potential fix, although I'm not entirely sure if this issue is masking another underlying problem. Try it and see how it goes.
> 
> see [907f8ce](https://github.com/TheWicklowWolf/LidaTube/commit/907f8ceda2909c574fa433fa511310653c889ac1)

This fixed the "Error Downloading: '<' not supported between instances of 'int' and 'str'" problem!

I have not tested on the entire wanted list but now get the "download complete" in the UI

logs show this repeating pattern for every album so far (not expecting a success on everything)
![image](https://github.com/TheWicklowWolf/LidaTube/assets/5973469/34def97f-98da-4cf5-a573-34e543ce29e0)

will test on a larger set of wanted

**Comment by TheWicklowWolf** [comment]
So this is weird.
When you refresh the wanted list from lidarr, the flow is like this:

- Request wanted album list from lidarr -> this is working for you
- Request missing tracks for each album -> this is not for some reason

What version of Lidarr are you using?

**Comment by TheWicklowWolf** [comment]
If you are using the latest version, you'll need to have a look at the lidarr logs for more info. 
I'd suggest clearing the Lidarr logs, temporarily set logging to trace, then tigger lidatube to get the wanted list. 
And then check the logs for anything relevant to api calls etc. 
(don't forget to turn off trace logging after)

**Comment by stetay2233** [comment]
> If you are using the latest version, you'll need to have a look at the lidarr logs for more info. I'd suggest clearing the Lidarr logs, temporarily set logging to trace, then tigger lidatube to get the wanted list. And then check the logs for anything relevant to api calls etc. (don't forget to turn off trace logging after)

was on develop moved to latest and now on 2.1.7.4030

from the logs (was same on develop and latest):

2024-04-05 12:40:57.8|Trace|Http|Res: 108 [GET] /api/v1/wanted/missing?includeArtist=true&apikey=(removed)&page=4&sortKey=artists.sortname&sortDirection=ascending: 200.OK (7424 ms)
2024-04-05 12:40:57.8|Debug|Api|[GET] /api/v1/wanted/missing?includeArtist=true&apikey=(removed)&page=4&sortKey=artists.sortname&sortDirection=ascending: 200.OK (7424 ms)
2024-04-05 12:40:57.8|Trace|Http|Req: 111 [GET] /api/v1/wanted/missing?includeArtist=true&apikey=(removed)&page=5&sortKey=artists.sortname&sortDirection=ascending (from 192.168.1.216 python-requests/2.31.0)
2024-04-05 12:40:57.8|Debug|Lidarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2024-04-05 12:41:05.2|Trace|Http|Res: 111 [GET] /api/v1/wanted/missing?includeArtist=true&apikey=(removed)&page=5&sortKey=artists.sortname&sortDirection=ascending: 200.OK (7374 ms)
2024-04-05 12:41:05.2|Debug|Api|[GET] /api/v1/wanted/missing?includeArtist=true&apikey=(removed)&page=5&sortKey=artists.sortname&sortDirection=ascending: 200.OK (7374 ms)
2024-04-05 12:41:05.2|Trace|Http|Req: 112 [GET] /api/v1/wanted/missing?includeArtist=true&apikey=(removed)&page=6&sortKey=artists.sortname&sortDirection=ascending (from 192.168.1.216 python-requests/2.31.0)
2024-04-05 12:41:05.2|Debug|Lidarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.

**Comment by TheWicklowWolf** [comment]
That shows the first API call `/api/v1/wanted/missing` was a success, you're looking for any reference to `/api/v1/track` to see whats happening in the API call that gets the list missing tracks.
Also what is in the logs for LidaTube when you just refresh the wanted list?

**Comment by TheWicklowWolf** [comment]
You might need to clone the source code and run it locally yourself and see what the issue is when you set through the code...

**Comment by TheWicklowWolf** [comment]
Assuming this is closed, re-open with any additional information if not.

**Comment by stetay2233** [comment]
sorry for the delay, was working on my setup, nuked the whole lidarr instance and then repulled the latest image and back up and working. So clearly even though there was no specific errors in lidarr logs, there is something wrong with my old instance as swapping between them brings the issues back
